---

- name: Playbook to install generic tools
  hosts: pvt 
  gather_facts: yes
  become: yes  #doing in root mode not admin
  vars: 
    TFROM: 1.8.5
  tasks:
  - name: check the hostnames
    shell: cat /etc/lsb-release
  - name: perform apt update 
    shell: apt-get update
  - name: install tools
    shell: apt-get install -y unzip jq stress net-tools

